### ISSUE TITLE
Username available?

### ISSUE THREAD

**Issue by EMBYRDEV** [Embyr/Embyr#1]
Would you be happy to let me use the username "Embyr" instead? I am pretty active on here mostly in private repos but I'm standardizing all my stuff on the embyr.sh domain and all my handles to "Embyr " where I can.

I'm happy to compensate you for it.

**Comment by Embyr** [comment]
I apologize it has taken me so long to reply and thank you for your interest but I cannot give up the name.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
